name: Say Hello

on:
  push:
    branches:
      - maain
  
jobs:
  hello-world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo del menasaje        
        run: |
          echo "Hello world"